// frontend/src/lib/components/common/emptyState/EmptyState.svelte
<script lang="ts">
	import type { Snippet } from 'svelte'
	import Button from '../button/Button.svelte'

	interface Props {
		icon: any
		title: string
		description?: string
		action?: {
			label: string
			icon?: any
			onClick: () => void
			aiId?: string
			aiDescription?: string
		}
		children?: Snippet
	}

	let { icon: Icon, title, description, action, children }: Props = $props()
</script>

<div
	class="flex flex-col items-center justify-center gap-4 rounded-lg border border-dashed border-border-light px-6 py-16 text-center"
>
	<div class="text-secondary">
		<Icon size={32} />
	</div>
	<div class="flex flex-col gap-1 max-w-md">
		<div class="text-sm font-semibold text-emphasis">{title}</div>
		{#if description}
			<div class="text-xs text-secondary">{description}</div>
		{/if}
	</div>
	{#if action}
		<Button
			unifiedSize="md"
			variant="accent"
			startIcon={action.icon ? { icon: action.icon } : undefined}
			onClick={action.onClick}
			aiId={action.aiId}
			aiDescription={action.aiDescription}
		>
			{action.label}
		</Button>
	{/if}
	{@render children?.()}
</div>

// ai_evals/fixtures/frontend/global/initial/analytics_dashboard/frontend/components/EmptyState.tsx
import React from 'react'

interface EmptyStateProps {
	title: string
	description?: string
	icon?: string
	action?: React.ReactNode
}

export const EmptyState: React.FC<EmptyStateProps> = ({
	title,
	description,
	icon = '📊',
	action
}) => {
	return (
		<div className="flex flex-col items-center justify-center rounded-lg border border-dashed border-gray-300 bg-white py-12 text-center">
			<div className="text-3xl" aria-hidden>
				{icon}
			</div>
			<h3 className="mt-3 text-sm font-semibold text-gray-700">{title}</h3>
			{description ? (
				<p className="mt-1 max-w-sm text-sm text-gray-500">{description}</p>
			) : null}
			{action ? <div className="mt-4">{action}</div> : null}
		</div>
	)
}
